### ISSUE TITLE
Include ability to view and download blob storage files

### ISSUE THREAD

**Issue by markysoft** [nhsuk/pharmacy-data-etl#3]
At present the repository contains no way to list or view the files uploaded to blob storage.
A small library should be created to assist with this.

**Comment by st3v3nhunt** [comment]
Does using https://azure.microsoft.com/en-us/features/storage-explorer/ cover the issue?

**Comment by st3v3nhunt** [comment]
Closing as https://azure.microsoft.com/en-us/features/storage-explorer/ is a cross platform tool for managing Azure storage.
